Templates Plugins on Stack
stack-spot/zup-kotlin-stack pull request #3
Opened 2022-03-28 14:21 UTC by rodrigofernandozup

Add Templates Plugins on Stack

2022-03-28 14:52 UTC, ricardojsilva requested changes
Please verify the suggestion

2022-03-28 14:52 UTC, ricardojsilva commented on stack.yaml
> +description: Stack of Kotlin with Spring for application and plugins that uses EKS as base
```suggestion
description: Stack that provides the ability to build applications with Kotlin and Spring, beyond to provide the minimum setup to deploy the app on AWS EKS via CDK
```

2022-03-28 14:52 UTC, ricardojsilva commented on stack.yaml
> +description: Stack of Kotlin with Spring for application and plugins that uses EKS as base
Verify if it makes sense.

2022-03-28 17:26 UTC, ricardojsilva approved these changes

2022-03-29 13:25 UTC, ze12augusto approved these changes

2022-03-29 13:25 UTC, merged